from .stages import (
    NODE_CLASS_MAPPINGS as _STAGE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _STAGE_NAMES,
)

NODE_CLASS_MAPPINGS: dict = {}
NODE_CLASS_MAPPINGS.update(_STAGE_NODES)

NODE_DISPLAY_NAME_MAPPINGS: dict = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_STAGE_NAMES)
