import ast
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = "Comfy-Org/comfy-cli"
VENDOR = Path(__file__).resolve().parent.parent / "runners" / "vendor"
FILES = {
    "comfy_cli/workflow_to_api.py": "workflow_to_api.py",
    "comfy_cli/cql/promoted.py": "cql_promoted.py",
}
ENGINE = "comfy_cli/cql/engine.py"
IMPORTS = [
    (re.compile(r"from comfy_cli\.cql\.engine import"), "from .cql_engine import"),
    (re.compile(r"from comfy_cli\.cql import promoted as"), "from . import cql_promoted as"),
]


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def resolve_sha(ref: str) -> str:
    return json.loads(fetch(f"https://api.github.com/repos/{REPO}/commits/{ref}"))["sha"]


def header(sha: str, path: str) -> str:
    return (
        f"# Vendored from {REPO}@{sha} {path} (GPL-3.0).\n"
        f"# Generated by scripts/sync_comfy_cli_converter.py; re-run it instead of editing.\n\n"
    )


def engine_names(sources: list[str]) -> list[str]:
    names = []
    for src in sources:
        for node in ast.walk(ast.parse(src)):
            if isinstance(node, ast.ImportFrom) and node.module == "comfy_cli.cql.engine" and node.col_offset == 0:
                names += [a.name for a in node.names if a.name not in names]
    return names


def extract_engine(src: str, wanted: list[str]) -> str:
    tree = ast.parse(src)
    defs = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            defs[node.name] = node
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            for t in node.targets if isinstance(node, ast.Assign) else [node.target]:
                if isinstance(t, ast.Name):
                    defs[t.id] = node
    keep, stack = set(), list(wanted)
    while stack:
        name = stack.pop()
        if name not in defs:
            sys.exit(f"{ENGINE}: {name} is not a top-level definition; extend the sync script")
        node = defs[name]
        if node in keep:
            continue
        keep.add(node)
        stack += [n.id for n in ast.walk(node) if isinstance(n, ast.Name) and n.id in defs]
    lines = src.splitlines(keepends=True)
    return "from __future__ import annotations\n\n\n" + "\n\n".join(
        "".join(lines[n.lineno - 1:n.end_lineno]) for n in tree.body if n in keep
    )


def main() -> None:
    sha = resolve_sha(sys.argv[1] if len(sys.argv) > 1 else "main")
    raw = f"https://raw.githubusercontent.com/{REPO}/{sha}/"
    sources = {path: fetch(raw + path) for path in FILES}
    for path, src in sources.items():
        for pattern, repl in IMPORTS:
            src = pattern.sub(repl, src)
        if re.search(r"^\s*(from|import) comfy_cli\b", src, re.M):
            sys.exit(f"{path}: unhandled comfy_cli import; extend IMPORTS")
        (VENDOR / FILES[path]).write_text(header(sha, path) + src, encoding="utf-8", newline="\n")
    engine = extract_engine(fetch(raw + ENGINE), engine_names(list(sources.values())))
    (VENDOR / "cql_engine.py").write_text(header(sha, ENGINE) + engine, encoding="utf-8", newline="\n")
    print(f"synced {REPO}@{sha}")


if __name__ == "__main__":
    main()
